### PR TITLE
BaSP-MR-199: Main styles

### PR DESCRIPTION
**Pull request by victoriassol**
Changed the navbar to be in header
Changed response modal to be on bottom right
Added consistency throughout tables
Consistency throughout forms
Added a Logout icon

### CODE REVIEW

**Review by santimenendez98 — COMMENTED** [review]
The login form, activity table, classes table, and trainers looks a bit up, it should be in the center of the layout. But everything else is very good.

**Comment by FontanR** [comment]
the loader in trainers appears top left section of the screen
but i am not sure if that fix should belong to this ticket

everything else works fine and the page is looking really good with this changes
great work

**Review by jramire5 — COMMENTED** [review]
I think the page is looking much better. Everything is looking good.
Two things:
image
-Here this buttons appear duplicated. It's just in the home, before signin in
-We could update the favicon.ico, and put the new logo

**Review by FontanR — APPROVED** [review]

**Review by jramire5 — APPROVED** [review]
Nice! LGTM!

**Review by IgnacioGalceran — APPROVED** [review]
Good job

**Pull request merged**
