### PR TITLE
BaSP-MR-216: Restructuring admin and member

### PR DESCRIPTION
**Pull request by WalterArielPavicich**
https://trello.com/c/oFXYDXe2

The following functionalities have been added:
- Admin should not be able to modify member membership.
- Admin should not be able to add a member. 
- Added a functional toggle to allow the admin to enable/disable the membership status.
- Admin will not be able to add, delete or edit subscriptions.
- The member must be inactive when created and cannot view the grid and subscriptions until activated by the administrator.

### CODE REVIEW

**Review by santimenendez98 — COMMENTED** [review]
When you access a schedule or subscriptions page and update the page, it crashes and sends you a message in the console (isActive = undefined)

**Comment by WalterArielPavicich** [comment]
fixed! 😄

**Comment by FontanR** [comment]
admin shouldnt be able to create, edit or delete a subscription anymore, only members can change their own subscriptions
maybe we can implement the toggle button for trainers and should be active for default when created

**Review by FontanR — APPROVED** [review]

**Review by IgnacioGalceran — APPROVED** [review]
Nice job

**Pull request merged**
